[package]
name = "memdb_test"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4", features = ["derive"] }
moka = { version = "0.12", features = ["sync"] }
dashmap = "6.1"
papaya = "0.1"
flurry = "0.5"
rand = "0.8"
